# Change these first
owner: pachakutiq199999 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: pachakutiq199999

sites:
  - name: Justmojito.com
    url: https://justmojito.com
    icon: https://mojito.alwaysdata.net/upptimesitesfavicon.ico
    maxResponseTime: 5000
  - name: Justmojito.xyz
    url: https://justmojito.xyz
    icon: https://mojito.alwaysdata.net/upptimesitesfavicon.ico
    maxResponseTime: 5000
  - name: Mojito EU
    url: https://mojito.eu.org
    icon: https://mojito.alwaysdata.net/upptimesitesfavicon.ico
    maxResponseTime: 5000
  - name: Mail
    url: https://mail.justmojito.com
    icon: https://mojito.alwaysdata.net/upptimesitesfavicon.ico
    maxResponseTime: 5000
  - name: RSS
    url: https://rss.orgs.hk
    icon: https://mojito.alwaysdata.net/upptimesitesfavicon.ico
    maxResponseTime: 5000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.now.cc
  # baseUrl: /your-repo-name
  logoUrl: https://uptime.now.cc/logo-512.png
  name: Upptime
  favicon: https://mojito.alwaysdata.net/upptimefavicon-32x32.png
  introTitle: "**Upptime Monitor**"
  introMessage: This status page shows **real-time** data of servers. [GitHub repository](https://github.com/pachakutiq199999/upptime).

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
